---
# Specify component versions to install
version:
  kubernetes: 1.32.0  # https://kubernetes.io/releases/
  containerd: 2.1.2   # https://github.com/containerd/containerd/releases
  runc: 1.3.0         # https://github.com/opencontainers/runc/releases
  cni: 1.7.1          # https://github.com/containernetworking/plugins/releases
  crictl: 1.32.0      # https://github.com/kubernetes-sigs/cri-tools/releases
# Constant values, do not change
const:
  kubeconfig: /etc/kubernetes/admin.conf
  kubeadm_config: /etc/kubernetes/kubeadm-config.yaml