---
- name: Copy multipath config file
  copy:
    src: multipath.conf
    dest: /etc/multipath.conf
  notify:
    - Restart multipath-tools

- name: Install NFS and iSCSI packages
  apt:
    name:
      - nfs-common
      - open-iscsi
      - lsscsi
      - sg3-utils
      - multipath-tools
      - scsitools

- name: Enable multipath-tools service
  systemd:
    name: multipath-tools
    enabled: true
    state: started

- name: Enable open-iscsi service
  systemd:
    name: open-iscsi
    enabled: true
    state: started
